import { useState, useEffect } from "react";
import { Copy, Download, FileCode, Check, RefreshCw, Upload, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";

interface Stream {
  id: string;
  name: string;
  input_url: string;
  input_type: string;
}

interface StreamMapping {
  name: string;
  proxyUrl: string;
  originalUrl: string;
}

interface NginxProxyGeneratorProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  serverIp: string;
  httpPort: string;
}

export const NginxProxyGenerator = ({ open, onOpenChange, serverIp, httpPort }: NginxProxyGeneratorProps) => {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const [streams, setStreams] = useState<Stream[]>([]);
  const [loading, setLoading] = useState(false);
  const [deploying, setDeploying] = useState(false);
  const [deployResult, setDeployResult] = useState<{ commands: string[]; streamMappings: StreamMapping[] } | null>(null);

  const fetchStreams = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("streams")
      .select("id, name, input_url, input_type")
      .order("name", { ascending: true });

    if (error) {
      toast({ title: "Greška", description: "Nije moguće učitati streamove", variant: "destructive" });
    } else {
      // Filter only external streams (HLS/HTTP sources)
      const externalStreams = (data || []).filter(s => 
        s.input_type === 'hls' || 
        s.input_type === 'http' || 
        s.input_url?.startsWith('http')
      );
      setStreams(externalStreams);
    }
    setLoading(false);
  };

  useEffect(() => {
    if (open) {
      fetchStreams();
    }
  }, [open]);

  const generateProxyLocations = () => {
    if (streams.length === 0) {
      return `    # Nema eksternih streamova u bazi
    # Dodaj streamove s HLS/HTTP izvorom u Streams sekciji`;
    }

    return streams.map(stream => {
      const streamName = stream.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
      const inputUrl = stream.input_url.trim();
      
      // Parse the base URL
      let baseUrl = inputUrl;
      if (inputUrl.endsWith('.m3u8') || inputUrl.endsWith('.ts')) {
        baseUrl = inputUrl.substring(0, inputUrl.lastIndexOf('/'));
      }
      if (baseUrl.endsWith('/')) {
        baseUrl = baseUrl.slice(0, -1);
      }

      return `    # Stream: ${stream.name}
    location /proxy/${streamName}/ {
        proxy_pass ${baseUrl}/;
        proxy_http_version 1.1;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_cache off;
        
        # CORS
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS';
        
        # Cache za .ts segmente
        location ~ \\.ts$ {
            proxy_pass ${baseUrl};
            proxy_cache_valid 200 1h;
        }
    }`;
    }).join('\n\n');
  };

  const generateConfig = () => {
    const port = httpPort || '8080';
    const ip = serverIp || 'localhost';

    return `# ============================================
# NGINX Proxy Configuration for External Streams
# Generated by StreamPanel
# Server: ${ip}:${port}
# Streams: ${streams.length}
# ============================================

# Dodaj ovo u tvoj postojeći server block na portu ${port}
# ili kreiraj novi server block

server {
    listen ${port};
    server_name ${ip};

    # CORS headers
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods 'GET, OPTIONS' always;
    add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;

    # Handle OPTIONS preflight
    if ($request_method = 'OPTIONS') {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS';
        add_header Access-Control-Max-Age 1728000;
        add_header Content-Type 'text/plain charset=UTF-8';
        add_header Content-Length 0;
        return 204;
    }

${generateProxyLocations()}

    # Health check
    location /proxy/health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}

# ============================================
# Korištenje:
#
# Originalni URL:
#   http://188.64.28.110/stream/channel/index.m3u8
#
# Proxy URL (skriva originalni IP):
#   http://${ip}:${port}/proxy/stream_name/index.m3u8
#
# Instalacija:
# 1. Kopiraj ovu konfiguraciju u:
#    /etc/nginx/sites-available/stream-proxy
#
# 2. Omogući site:
#    ln -s /etc/nginx/sites-available/stream-proxy /etc/nginx/sites-enabled/
#
# 3. Testiraj i reload:
#    nginx -t && systemctl reload nginx
#
# ============================================
# Stream URL mappings:
${streams.map(s => {
  const streamName = s.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
  return `# ${s.name}: http://${ip}:${port}/proxy/${streamName}/index.m3u8`;
}).join('\n')}
# ============================================
`;
  };

  const config = generateConfig();

  const handleCopy = () => {
    navigator.clipboard.writeText(config);
    setCopied(true);
    toast({ title: "Kopirano", description: "Proxy konfiguracija kopirana" });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([config], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'stream-proxy.conf';
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Preuzeto", description: "stream-proxy.conf datoteka preuzeta" });
  };

  const handleDeploy = async () => {
    setDeploying(true);
    setDeployResult(null);
    
    try {
      const { data, error } = await supabase.functions.invoke('deploy-proxy-config', {
        body: { serverIp, httpPort, action: 'deploy' }
      });

      if (error) throw error;

      if (data.success) {
        setDeployResult({
          commands: [],
          streamMappings: data.streamMappings || []
        });
        toast({ 
          title: "Uspješno deplojirano!", 
          description: data.message || `Config primijenjen na server.`
        });
      } else {
        throw new Error(data.error || 'Deploy failed');
      }
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      toast({ title: "Greška", description: errorMessage, variant: "destructive" });
    } finally {
      setDeploying(false);
    }
  };

  const handleTestConnection = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('deploy-proxy-config', {
        body: { serverIp, httpPort, action: 'health' }
      });

      if (error) throw error;

      if (data.success) {
        toast({ title: "Agent dostupan!", description: "Povezivanje uspješno." });
      } else {
        throw new Error(data.error || 'Agent not reachable');
      }
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      toast({ 
        title: "Agent nedostupan", 
        description: `${errorMessage}. Instaliraj agent na server.`, 
        variant: "destructive" 
      });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[900px] max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileCode className="h-5 w-5 text-primary" />
            Nginx Proxy Konfiguracija ({streams.length} streamova)
          </DialogTitle>
        </DialogHeader>
        
        {/* Agent Install Instructions */}
        <div className="mb-3 p-3 rounded-lg bg-muted/50 border border-border">
          <p className="text-xs font-medium mb-2">1. Instaliraj agent na server (jednom):</p>
          <code className="text-xs bg-background p-2 rounded block mb-2">
            curl -sSL https://vps-stream-panel.lovable.app/install-agent.sh | AGENT_SECRET=your_secret sudo bash
          </code>
          <p className="text-xs text-muted-foreground">Zamijeni <code>your_secret</code> sa sigurnom lozinkom i dodaj istu u Secrets kao AGENT_SECRET</p>
        </div>

        <div className="flex flex-wrap gap-2 mb-3">
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? <Check className="h-4 w-4 mr-1" /> : <Copy className="h-4 w-4 mr-1" />}
            {copied ? 'Kopirano!' : 'Kopiraj'}
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownload}>
            <Download className="h-4 w-4 mr-1" />
            Preuzmi
          </Button>
          <Button variant="ghost" size="sm" onClick={fetchStreams} disabled={loading}>
            <RefreshCw className={`h-4 w-4 mr-1 ${loading ? 'animate-spin' : ''}`} />
            Osvježi
          </Button>
          <Button variant="secondary" size="sm" onClick={handleTestConnection}>
            Test Agent
          </Button>
          <Button 
            variant="default" 
            size="sm" 
            onClick={handleDeploy} 
            disabled={deploying || streams.length === 0}
          >
            {deploying ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Upload className="h-4 w-4 mr-1" />}
            {deploying ? 'Deployam...' : 'Deploy na Server'}
          </Button>
        </div>

        {deployResult && deployResult.streamMappings.length > 0 && (
          <div className="mb-3 p-3 rounded-lg bg-green-500/10 border border-green-500/30">
            <p className="text-sm font-medium text-green-600 mb-2">✓ Config uspješno primijenjen!</p>
            <p className="text-xs font-medium mb-1">Proxy URL-ovi:</p>
            <div className="space-y-1">
              {deployResult.streamMappings.map((s, i) => (
                <div key={i} className="text-xs">
                  <span className="text-muted-foreground">{s.name}:</span>{' '}
                  <code className="text-primary">{s.proxyUrl}</code>
                </div>
              ))}
            </div>
          </div>
        )}

        <div className="flex-1 overflow-auto rounded-lg bg-muted/50 border border-border">
          <pre className="p-4 text-xs font-mono text-foreground whitespace-pre overflow-x-auto">
            {config}
          </pre>
        </div>

        <p className="text-xs text-muted-foreground mt-2">
          Konfiguracija proxira sve eksterne streamove iz baze kroz tvoj server. Originalni IP-evi su skriveni.
        </p>
      </DialogContent>
    </Dialog>
  );
};
