import { useState } from "react";
import { Copy, Download, FileCode, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";

interface NginxConfigGeneratorProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  settings: {
    streamServerIp: string;
    streamServerPort: string;
    streamHttpPort: string;
    streamHlsPath: string;
    streamUseSSL: boolean;
    hlsSegmentDuration: string;
    hlsPlaylistLength: string;
    recordingsPath: string;
    maxBitrate: string;
    enableDVR: boolean;
    dvrDuration: string;
    enableAuth: boolean;
    streamKeyPrefix: string;
    enableTranscoding: boolean;
    transcodingPreset: string;
    transcodingBitrate: string;
  };
}

export const NginxConfigGenerator = ({ open, onOpenChange, settings }: NginxConfigGeneratorProps) => {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);

  const generateConfig = () => {
    const hlsPath = settings.streamHlsPath || '/live';
    const httpPort = settings.streamHttpPort || '8080';
    const rtmpPort = settings.streamServerPort || '1935';
    const segmentDuration = settings.hlsSegmentDuration || '2';
    const playlistLength = settings.hlsPlaylistLength || '6';
    const recordingsPath = settings.recordingsPath || '/var/www/recordings';

    return `# ============================================
# NGINX-RTMP Streaming Server Configuration
# Generated by StreamPanel
# ============================================

# Worker processes (set to auto for optimal performance)
worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

# RTMP Configuration
rtmp {
    server {
        listen ${rtmpPort};
        chunk_size 4096;
        max_connections 1000;

        # Live streaming application
        application live {
            live on;
            
            # Enable HLS
            hls on;
            hls_path /var/www/hls${hlsPath};
            hls_fragment ${segmentDuration}s;
            hls_playlist_length ${parseInt(segmentDuration) * parseInt(playlistLength)}s;
            hls_cleanup on;
            hls_continuous on;
            
            # HLS variants for ABR (Adaptive Bitrate)
            hls_variant _low BANDWIDTH=500000;
            hls_variant _mid BANDWIDTH=1500000;
            hls_variant _high BANDWIDTH=4000000;
            
${settings.enableDVR ? `            # DVR/Recording
            record all;
            record_path ${recordingsPath};
            record_suffix _%Y-%m-%d_%H-%M-%S.flv;
            record_max_size 5120M;
            record_interval ${settings.dvrDuration || '24'}h;
` : '            # DVR disabled'}

${settings.enableAuth ? `            # Authentication
            on_publish http://localhost/auth/publish;
            on_publish_done http://localhost/auth/done;
            on_play http://localhost/auth/play;
` : '            # Authentication disabled'}

${settings.enableTranscoding ? `            # Transcoding
            exec ffmpeg -i rtmp://localhost/${rtmpPort}/$name
                -c:v libx264 -preset ${settings.transcodingPreset || 'medium'}
                -b:v ${settings.transcodingBitrate || '4000'}k
                -c:a aac -b:a 128k
                -f flv rtmp://localhost/${rtmpPort}/live/$name_transcoded;
` : '            # Transcoding disabled'}

            # Notify on stream events
            notify_method get;
            
            # Allow publishing from any
            allow publish all;
            allow play all;
        }

        # Recording playback
        application vod {
            play ${recordingsPath};
        }
    }
}

# HTTP Configuration
http {
    include mime.types;
    default_type application/octet-stream;

    # Performance optimizations
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript application/x-mpegurl video/mp2t;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    server {
        listen ${httpPort};
        server_name ${settings.streamServerIp || 'localhost'};

        # CORS headers for HLS
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS';
        add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header Access-Control-Expose-Headers 'Content-Length,Content-Range';

        # HLS streaming
        location ${hlsPath} {
            alias /var/www/hls${hlsPath};
            
            # MIME types for HLS
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            
            # Cache control
            add_header Cache-Control no-cache;
            expires -1;
        }

        # RTMP statistics
        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }

        location /stat.xsl {
            root /usr/share/nginx/html;
        }

        # Control interface
        location /control {
            rtmp_control all;
        }

        # Health check
        location /health {
            access_log off;
            return 200 'OK';
            add_header Content-Type text/plain;
        }

        # VOD playback
        location /vod {
            alias ${recordingsPath};
        }
    }

${settings.streamUseSSL ? `
    # HTTPS Server (SSL)
    server {
        listen 443 ssl http2;
        server_name ${settings.streamServerIp || 'localhost'};

        ssl_certificate /etc/letsencrypt/live/${settings.streamServerIp}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/${settings.streamServerIp}/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Same locations as HTTP server
        location ${hlsPath} {
            alias /var/www/hls${hlsPath};
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }
    }
` : '    # SSL disabled - enable in settings for HTTPS support'}
}

# ============================================
# Installation commands:
# 
# 1. Install nginx with RTMP module:
#    apt-get install nginx libnginx-mod-rtmp
#
# 2. Create directories:
#    mkdir -p /var/www/hls${hlsPath}
#    mkdir -p ${recordingsPath}
#    chown -R www-data:www-data /var/www/hls
#    chown -R www-data:www-data ${recordingsPath}
#
# 3. Copy this config to:
#    /etc/nginx/nginx.conf
#
# 4. Test and restart:
#    nginx -t && systemctl restart nginx
#
# 5. Stream to:
#    rtmp://${settings.streamServerIp || 'YOUR_SERVER_IP'}:${rtmpPort}/live/STREAM_KEY
#
# 6. Watch at:
#    http://${settings.streamServerIp || 'YOUR_SERVER_IP'}:${httpPort}${hlsPath}/STREAM_KEY/index.m3u8
# ============================================
`;
  };

  const config = generateConfig();

  const handleCopy = () => {
    navigator.clipboard.writeText(config);
    setCopied(true);
    toast({ title: "Kopirano", description: "Nginx konfiguracija kopirana" });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([config], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'nginx.conf';
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Preuzeto", description: "nginx.conf datoteka preuzeta" });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[900px] max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileCode className="h-5 w-5 text-primary" />
            Nginx RTMP Konfiguracija
          </DialogTitle>
        </DialogHeader>
        
        <div className="flex gap-2 mb-3">
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? <Check className="h-4 w-4 mr-1" /> : <Copy className="h-4 w-4 mr-1" />}
            {copied ? 'Kopirano!' : 'Kopiraj'}
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownload}>
            <Download className="h-4 w-4 mr-1" />
            Preuzmi nginx.conf
          </Button>
        </div>

        <div className="flex-1 overflow-auto rounded-lg bg-muted/50 border border-border">
          <pre className="p-4 text-xs font-mono text-foreground whitespace-pre overflow-x-auto">
            {config}
          </pre>
        </div>

        <p className="text-xs text-muted-foreground mt-2">
          Konfiguracija je generirana na temelju tvojih postavki. Kopiraj je na server u <code>/etc/nginx/nginx.conf</code>
        </p>
      </DialogContent>
    </Dialog>
  );
};
