import { useState, useEffect } from "react";
import { Copy, Download, FileCode, Check, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";

interface Stream {
  id: string;
  name: string;
  input_url: string;
  input_type: string;
}

interface NginxProxyGeneratorProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  serverIp: string;
  httpPort: string;
}

export const NginxProxyGenerator = ({ open, onOpenChange, serverIp, httpPort }: NginxProxyGeneratorProps) => {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const [streams, setStreams] = useState<Stream[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchStreams = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("streams")
      .select("id, name, input_url, input_type")
      .order("name", { ascending: true });

    if (error) {
      toast({ title: "Greška", description: "Nije moguće učitati streamove", variant: "destructive" });
    } else {
      // Filter only external streams (HLS/HTTP sources)
      const externalStreams = (data || []).filter(s => 
        s.input_type === 'hls' || 
        s.input_type === 'http' || 
        s.input_url?.startsWith('http')
      );
      setStreams(externalStreams);
    }
    setLoading(false);
  };

  useEffect(() => {
    if (open) {
      fetchStreams();
    }
  }, [open]);

  const generateProxyLocations = () => {
    if (streams.length === 0) {
      return `    # Nema eksternih streamova u bazi
    # Dodaj streamove s HLS/HTTP izvorom u Streams sekciji`;
    }

    return streams.map(stream => {
      const streamName = stream.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
      const inputUrl = stream.input_url.trim();
      
      // Parse the base URL
      let baseUrl = inputUrl;
      if (inputUrl.endsWith('.m3u8') || inputUrl.endsWith('.ts')) {
        baseUrl = inputUrl.substring(0, inputUrl.lastIndexOf('/'));
      }
      if (baseUrl.endsWith('/')) {
        baseUrl = baseUrl.slice(0, -1);
      }

      return `    # Stream: ${stream.name}
    location /proxy/${streamName}/ {
        proxy_pass ${baseUrl}/;
        proxy_http_version 1.1;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_cache off;
        
        # CORS
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS';
        
        # Cache za .ts segmente
        location ~ \\.ts$ {
            proxy_pass ${baseUrl};
            proxy_cache_valid 200 1h;
        }
    }`;
    }).join('\n\n');
  };

  const generateConfig = () => {
    const port = httpPort || '8080';
    const ip = serverIp || 'localhost';

    return `# ============================================
# NGINX Proxy Configuration for External Streams
# Generated by StreamPanel
# Server: ${ip}:${port}
# Streams: ${streams.length}
# ============================================

# Dodaj ovo u tvoj postojeći server block na portu ${port}
# ili kreiraj novi server block

server {
    listen ${port};
    server_name ${ip};

    # CORS headers
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods 'GET, OPTIONS' always;
    add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;

    # Handle OPTIONS preflight
    if ($request_method = 'OPTIONS') {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, OPTIONS';
        add_header Access-Control-Max-Age 1728000;
        add_header Content-Type 'text/plain charset=UTF-8';
        add_header Content-Length 0;
        return 204;
    }

${generateProxyLocations()}

    # Health check
    location /proxy/health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}

# ============================================
# Korištenje:
#
# Originalni URL:
#   http://188.64.28.110/stream/channel/index.m3u8
#
# Proxy URL (skriva originalni IP):
#   http://${ip}:${port}/proxy/stream_name/index.m3u8
#
# Instalacija:
# 1. Kopiraj ovu konfiguraciju u:
#    /etc/nginx/sites-available/stream-proxy
#
# 2. Omogući site:
#    ln -s /etc/nginx/sites-available/stream-proxy /etc/nginx/sites-enabled/
#
# 3. Testiraj i reload:
#    nginx -t && systemctl reload nginx
#
# ============================================
# Stream URL mappings:
${streams.map(s => {
  const streamName = s.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
  return `# ${s.name}: http://${ip}:${port}/proxy/${streamName}/index.m3u8`;
}).join('\n')}
# ============================================
`;
  };

  const config = generateConfig();

  const handleCopy = () => {
    navigator.clipboard.writeText(config);
    setCopied(true);
    toast({ title: "Kopirano", description: "Proxy konfiguracija kopirana" });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([config], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'stream-proxy.conf';
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Preuzeto", description: "stream-proxy.conf datoteka preuzeta" });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[900px] max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileCode className="h-5 w-5 text-primary" />
            Nginx Proxy Konfiguracija ({streams.length} streamova)
          </DialogTitle>
        </DialogHeader>
        
        <div className="flex gap-2 mb-3">
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? <Check className="h-4 w-4 mr-1" /> : <Copy className="h-4 w-4 mr-1" />}
            {copied ? 'Kopirano!' : 'Kopiraj'}
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownload}>
            <Download className="h-4 w-4 mr-1" />
            Preuzmi stream-proxy.conf
          </Button>
          <Button variant="ghost" size="sm" onClick={fetchStreams} disabled={loading}>
            <RefreshCw className={`h-4 w-4 mr-1 ${loading ? 'animate-spin' : ''}`} />
            Osvježi
          </Button>
        </div>

        <div className="flex-1 overflow-auto rounded-lg bg-muted/50 border border-border">
          <pre className="p-4 text-xs font-mono text-foreground whitespace-pre overflow-x-auto">
            {config}
          </pre>
        </div>

        <p className="text-xs text-muted-foreground mt-2">
          Konfiguracija proxira sve eksterne streamove iz baze kroz tvoj server. Originalni IP-evi su skriveni.
        </p>
      </DialogContent>
    </Dialog>
  );
};
